source "https://rubygems.org"

ruby  "2.7.1"

gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
gem "rack-test"
gem "minitest"
gem "minitest-reporters"
gem "redcarpet"
gem "bcrypt"

group :production do
  gem "puma"
end